package org.usfirst.frc.team166.robot.subsystems;

import edu.wpi.first.wpilibj.vision.VisionPipeline;

import org.opencv.core.Core;
import org.opencv.core.Mat;

/**
 * Vision class.
 *
 * <p>
 * An OpenCV pipeline generated by GRIP.
 *
 * @author GRIP
 */
public class Vision implements VisionPipeline {

	// Outputs

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	public void process() {
	}

	@Override
	public void process(Mat image) {
		// TODO Auto-generated method stub

	}

}
